name: Android CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Prepare secrets
      env:
        SECRET_API_KEY: ${{ secrets.SECRET_API_KEY }}
        storePassword: ${{ secrets.STOREPASSWORD }}
        keyPassword: ${{ secrets.KEYPASSWORD }}
        keyAlias: ${{ secrets.KEYALIAS }}
        storeFile: ${{ secrets.STOREFILE }}
      run: |
        echo "${{ secrets.STOREFILE_B64 }}" > ../"${{ secrets.STOREFILE }}".asc

        gpg -d --passphrase "${{ secrets.STOREFILE_PASSWORD }}"  --batch ../"${{ secrets.STOREFILE }}".asc > ../Political-Preparedness/"${{ secrets.STOREFILE }}"
        
        echo API_KEY=${{ env.SECRET_API_KEY }} > ./local.properties
        echo storePassword=${{ env.storePassword }} >> ./local.properties
        echo keyPassword=${{ env.keyPassword }} >> ./local.properties
        echo keyAlias=${{ env.keyAlias }} >> ./local.properties
        echo storeFile=../${{ env.storeFile }} >> ./local.properties

#    - name: Build with Gradle
#      run: ./gradlew build

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ./local.properties
          ../Political-Preparedness/"${{ secrets.STOREFILE }}"
        key: secret-files

  run-units:
  
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ./local.properties
          ../Political-Preparedness/"${{ secrets.STOREFILE }}"
        key: secret-files

    - name: Run Unit Tests
      run: ./gradlew app:testReleaseUnitTest --stacktrace
      
#  run-espresso:
  
#    runs-on: ubuntu-latest
    
#    steps:
#    - name: Run espresso
#    - uses: reactivecircus/android-emulator-runner@v2
#      with:
#        api-level: 27
#        target: default
#        arch: x86
#        profile: Pixel 3
#        run: ./gradlew connectedCheck --stacktrace
